version: '2'

volumes:
    worlds:

services:
    minecraft:
        image: magikcraft/scriptcraft:1.15.2
        container_name: minecraft
        ports:
            - '25565:25565'
            - '8086:8086'
        environment:
            - MINECRAFT_EULA_ACCEPTED=true
        volumes:
            - ./cache:/_server_/cache
            - worlds:/_server_/worlds
            # To load SMA plugins
            # Create a directory called scriptcraft-plugins and npm install any SMA plugins there
            # with npm install --prefix ./scriptcraft-plugins <package-name>
            # And uncomment the following line
            #     - ./scriptcraft-plugins:/_server_/scriptcraft-plugins
            # To add BPMN processes and handlers
            # Create a directory called bpmn and put them in there
            # And uncomment the following line:
            # - ./bpmn:/_server_/plugins/CamundaPlugin
